"""add sightings table

Revision ID: 330df7f825c8
Revises: f9c2f7dbb04f
Create Date: 2026-08-23 13:32:55.470209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330df7f825c8'
down_revision = 'f9c2f7dbb04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missing_person_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('sighting_date', sa.Date(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_persons.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sightings')
    # ### end Alembic commands ###
