"""add_is_banned_to_users

Revision ID: 970c25925ad8
Revises: eee43b2e664d
Create Date: 2026-10-06 11:09:32.590719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970c25925ad8'
down_revision = 'eee43b2e664d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
