"""add photo to missing person

Revision ID: da184127c612
Revises: 330df7f825c8
Create Date: 2026-09-28 13:45:28.220356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da184127c612'
down_revision = '330df7f825c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
